# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:59:39+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, constr


class FlexV2WebChannel(BaseModel):
    conversation_sid: Optional[
        constr(pattern=r'^CH[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string representing the [Conversation resource](https://www.twilio.com/docs/conversations/api/conversation-resource) created.',
    )
    identity: Optional[str] = Field(
        None,
        description='The unique string representing the User created and should be authorized to participate in the Conversation. For more details, see [User Identity & Access Tokens](https://www.twilio.com/docs/conversations/identity).',
    )


class V2WebChatsPostRequest(BaseModel):
    AddressSid: str = Field(
        ...,
        description='The SID of the Conversations Address. See [Address Configuration Resource](https://www.twilio.com/docs/conversations/api/address-configuration-resource) for configuration details. When a conversation is created on the Flex backend, the callback URL will be set to the corresponding Studio Flow SID or webhook URL in your address configuration.',
    )
    ChatFriendlyName: Optional[str] = Field(
        None,
        description="The Conversation's friendly name. See the [Conversation resource](https://www.twilio.com/docs/conversations/api/conversation-resource) for an example.",
    )
    CustomerFriendlyName: Optional[str] = Field(
        None,
        description="The Conversation participant's friendly name. See the [Conversation Participant Resource](https://www.twilio.com/docs/conversations/api/conversation-participant-resource) for an example.",
    )
    PreEngagementData: Optional[str] = Field(
        None, description='The pre-engagement data.'
    )
